<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>OmenGamingShell</AssemblyName>
    <RootNamespace>OmenGamingShell</RootNamespace>
    <Version>1.2.2</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\omen-icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.1.2" />
    <PackageReference Include="FuzzySharp" Version="2.0.2" />
    <PackageReference Include="csdl" Version="2.0.0-beta" />
    <PackageReference Include="csdl.Native" Version="2.0.0-pre" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="8.0.0" />
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\omen-wordmark-mask.png" />
    <Resource Include="Assets\omen-icon.png" />
    <Resource Include="..\.store-icons\*.svg" Link="Assets\Stores\%(Filename)%(Extension)" />
    <Content Include="games.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
</Project>
